package com.generationcamera.engine

/**
 * One era's full look at degree 10 (maximum intensity). Values come straight
 * from the Era Spec Table in ERA_ANALYSIS.md §0.2; the Degree Control scales
 * them via [EraEngine]. The color science itself lives in the era's .cube LUT
 * (assets/luts/era_<id>.cube, generated by tools/generate_assets.py).
 */
data class EraConfig(
    val id: String,            // "1900s" … "2026"
    val label: String,         // dial label
    val tagline: String,       // short look description shown under the dial
    val cameraModel: String,   // representative camera of the decade (photo caption)
    val shutterSound: String,  // res/raw sound name (synthesized, era-appropriate)
    val grain: Float,          // luminance grain amount
    val grainSize: Float,      // grain cell size in px
    val chromaNoise: Float,    // color noise (autochrome starch / VHS / CCD)
    val vignette: Float,
    val vignetteHard: Float,   // 0 soft lens falloff … 1 hard plate mask
    val softFocus: Float,      // pictorialist blur blend
    val halation: Float,
    val sharpness: Float,      // unsharp amount (2000s oversharpen)
    val scanline: Float,       // VHS scanlines + head-switch bar
    val chromaShift: Float,    // VHS chroma misregistration
    val flutter: Float,        // tape flutter (preview only)
    val flicker: Float,        // projector flicker (preview only)
    val weave: Float,          // gate weave UV amplitude (preview only)
    val dust: Float,           // dust/scratch overlay opacity
    val leak: Float,           // light-leak opacity
    val leakIndex: Int,        // which leak texture
    val resScale: Float,       // render-resolution factor (VHS ≈ 0.45)
) {
    val lutAsset get() = "luts/era_$id.cube"

    /** "1970s · Polaroid SX-70 · Faded print · light leaks" — stamped on photos. */
    val caption get() = "$label · $cameraModel · $tagline"

    // ---- Era-authentic control availability (researched, ERA_ANALYSIS.md §0.4).
    // Derived from the decade so history stays in one place:
    private val decadeStart: Int get() = id.take(4).toInt()

    /** Exposure was always the photographer's call: plate exposure time →
     *  aperture/shutter → EV compensation. Available in every era. */
    val hasExposure get() = true

    /** First consumer flashbulbs ship ~1930 (before that: magnesium powder). */
    val hasFlash get() = decadeStart >= 1930

    /** Mechanical self-timers ("Autoknips" era) become common in the 1930s. */
    val hasTimer get() = decadeStart >= 1930

    /** Consumer zoom arrives with 1960s power-zoom Super-8 cameras. */
    val hasZoom get() = decadeStart >= 1960

    /** On-image timestamps: 1990s camcorder OSD, 2000s digicam date stamp. */
    val hasTimestamp get() = decadeStart == 1990 || decadeStart == 2000

    /** Lens flip is always available — historically front cameras are a
     *  2000s invention, but hiding half the hardware hurt usability, so the
     *  selfie lens is a deliberate UX exception to era authenticity. */
    val hasSelfie get() = true

    /** Composition grid is a smartphone-app convention. */
    val hasGrid get() = decadeStart >= 2010
}

/**
 * Flat uniform block for the era über-shader: [EraConfig] × degree curves,
 * computed by [EraEngine]. Pure data — unit-testable, no GL types.
 */
data class EffectParams(
    val eraIndex: Int,
    val lutStrength: Float,
    val grain: Float,
    val grainSize: Float,
    val chromaNoise: Float,
    val vignette: Float,
    val vignetteHard: Float,
    val softFocus: Float,
    val halation: Float,
    val sharpness: Float,
    val scanline: Float,
    val chromaShift: Float,
    val flutter: Float,
    val flicker: Float,
    val weave: Float,
    val dust: Float,
    val leak: Float,
    val leakIndex: Int,
    val resScale: Float,
)
