package com.generationcamera.engine

/**
 * One era's full look at degree 10 (maximum intensity). Values come straight
 * from the Era Spec Table in ERA_ANALYSIS.md §0.2; the Degree Control scales
 * them via [EraEngine]. The color science itself lives in the era's .cube LUT
 * (assets/luts/era_<id>.cube, generated by tools/generate_assets.py).
 */
data class EraConfig(
    val id: String,            // "1900s" … "2020s"
    val label: String,         // dial label
    val tagline: String,       // short look description shown under the dial
    val grain: Float,          // luminance grain amount
    val grainSize: Float,      // grain cell size in px
    val chromaNoise: Float,    // color noise (autochrome starch / VHS / CCD)
    val vignette: Float,
    val vignetteHard: Float,   // 0 soft lens falloff … 1 hard plate mask
    val softFocus: Float,      // pictorialist blur blend
    val halation: Float,
    val sharpness: Float,      // unsharp amount (2000s oversharpen)
    val scanline: Float,       // VHS scanlines + head-switch bar
    val chromaShift: Float,    // VHS chroma misregistration
    val flutter: Float,        // tape flutter (preview only)
    val flicker: Float,        // projector flicker (preview only)
    val weave: Float,          // gate weave UV amplitude (preview only)
    val dust: Float,           // dust/scratch overlay opacity
    val leak: Float,           // light-leak opacity
    val leakIndex: Int,        // which leak texture
    val resScale: Float,       // render-resolution factor (VHS ≈ 0.45)
) {
    val lutAsset get() = "luts/era_$id.cube"
    val frameAsset get() = "frames/frame_$id.png"
}

/**
 * Flat uniform block for the era über-shader: [EraConfig] × degree curves,
 * computed by [EraEngine]. Pure data — unit-testable, no GL types.
 */
data class EffectParams(
    val eraIndex: Int,
    val lutStrength: Float,
    val grain: Float,
    val grainSize: Float,
    val chromaNoise: Float,
    val vignette: Float,
    val vignetteHard: Float,
    val softFocus: Float,
    val halation: Float,
    val sharpness: Float,
    val scanline: Float,
    val chromaShift: Float,
    val flutter: Float,
    val flicker: Float,
    val weave: Float,
    val dust: Float,
    val leak: Float,
    val leakIndex: Int,
    val resScale: Float,
)
